In [21]:
import pandas as pd
file_path=r"C:\Users\DELL\Desktop\Task_4.csv"
df=pd.read_csv(file_path)
print(df.to_string())

        price     area  bedrooms  bathrooms  stories   mainroad  guestroom   basement hotwaterheating airconditioning  parking   prefarea furnishingstatus
0    13300000   7420.0       4.0        NaN      3.0        NaN        NaN        NaN             NaN             yes      2.0     Haanji        furnished
1    12250000   8960.0       NaN        4.0      4.0        yes         no         no           Nakko             yes      NaN         no        furnished
2    12250000   9960.0       3.0        2.0      2.0        yes        NaN        yes              no           Naaji      2.0        yes   semi-furnished
3    12215000   7500.0       NaN        NaN      NaN        NaN         no        yes              no             yes      3.0        yes        furnished
4    11410000   7420.0       NaN        1.0      2.0        NaN  Of course        yes             NaN             yes      2.0         no              NaN
5    10850000      NaN       NaN        NaN      NaN        NaN         no     Haanji              no             yes      NaN        yes   semi-furnished
6    10150000      NaN       4.0        NaN      4.0        yes         no        NaN             NaN             yes      NaN        yes   semi-furnished
7    10150000  16200.0       5.0        3.0      2.0        NaN        NaN         no             NaN              no      0.0         no              NaN
8     9870000   8100.0       NaN        NaN      2.0        yes        yes        yes            Nope             NaN      2.0       Haan        furnished
9     9800000   5750.0       3.0        2.0      4.0        NaN        NaN          N              no             yes      1.0        NaN      unfurnished
10    9800000  13200.0       3.0        1.0      2.0        yes         no        NaN              no             NaN      2.0        yes              NaN
11    9681000      NaN       NaN        NaN      NaN        yes  Of course        NaN             NaN             NaN      2.0        NaN   semi-furnished
12    9310000   6550.0       4.0        NaN      NaN        NaN       ille         no             NaN             yes      1.0  Of course   semi-furnished
13    9240000   3500.0       4.0        NaN      NaN  Of course         no         no             yes              no      2.0         no        furnished
14    9240000   7800.0       NaN        2.0      2.0     Indeed         no         no             NaN             NaN      0.0        yes   semi-furnished
15    9100000      NaN       4.0        NaN      2.0        NaN        NaN        NaN              no              no      2.0         no   semi-furnished
16    9100000      NaN       NaN        2.0      2.0        yes        NaN        NaN              no             yes      NaN        yes      unfurnished
17    8960000   8500.0       NaN        2.0      4.0        yes         no        NaN              no             NaN      2.0      Nakko        furnished
18    8890000   4600.0       NaN        2.0      2.0        NaN        yes         no             NaN             yes      NaN       Nope        furnished
19    8855000      NaN       NaN        2.0      NaN        NaN         no          N              no             yes      NaN        NaN   semi-furnished
20    8750000   4320.0       3.0        NaN      2.0        NaN         no        yes             yes              no      2.0       Nope   semi-furnished
21    8680000   7155.0       3.0        NaN      NaN        yes          y        yes              no             NaN      NaN         no      unfurnished
22    8645000   8050.0       3.0        1.0      NaN        yes        NaN        NaN             Nah             NaN      1.0         no        furnished
23    8645000   4560.0       NaN        NaN      2.0        NaN        yes     Haanji             NaN             yes      1.0        NaN        furnished
24    8575000   8800.0       NaN        NaN      2.0        yep        NaN         no             NaN             yep      NaN         no        furnished
25    8540000      NaN       4.0        NaN      NaN        yes        NaN        NaN              no             yes      NaN        yes        furnished
26    8463000   6000.0       NaN        NaN      4.0        yes        NaN        NaN              no             yes      0.0        NaN              NaN
27    8400000   8875.0       NaN        NaN      NaN        yes        NaN      Naaji              no              no      NaN        NaN   semi-furnished
28    8400000   7950.0       5.0        2.0      2.0        NaN        NaN        NaN               Y              no      NaN         no              NaN
29    8400000      NaN       4.0        NaN      2.0       Haan         no        yes              no             yes      1.0        yes   semi-furnished
30    8400000   7475.0       NaN        2.0      4.0        NaN       ille        NaN             NaN             NaN      2.0         no              NaN
31    8400000   7000.0       3.0        1.0      4.0        yes         no         no              no               y      2.0        NaN   semi-furnished
32    8295000      NaN       4.0        2.0      2.0  Of course        NaN         no              no             yes      1.0        yes        furnished
33    8190000   5960.0       NaN        3.0      2.0        yes        yes        NaN               n             NaN      1.0         no              NaN
34    8120000   6840.0       NaN        NaN      2.0        yes        yes        NaN             NaN             yes      NaN         no        furnished
35    8080940   7000.0       3.0        2.0      NaN        NaN         no        NaN             NaN             yes      NaN         no        furnished
36    8043000   7482.0       NaN        NaN      3.0        yes         no        NaN             NaN             NaN      NaN        yes        furnished
37    7980000   9000.0       4.0        2.0      4.0        yes        NaN         no             NaN             NaN      2.0         no        furnished
38    7962500      NaN       NaN        1.0      4.0        NaN        NaN         no             NaN               y      2.0         no              NaN
39    7910000      NaN       4.0        NaN      NaN        NaN        NaN          n           FALSE             yes      1.0        NaN   semi-furnished
40    7875000   6550.0       3.0        NaN      2.0        NaN         no        yes              no             yes      NaN        yes        furnished
41    7840000   6360.0       3.0        2.0      4.0        yes        NaN        NaN             NaN             yes      0.0        NaN              NaN
42    7700000   6480.0       3.0        NaN      NaN        NaN        NaN         no              no             yes      2.0        NaN      unfurnished
43    7700000   6000.0       NaN        NaN      NaN        NaN         no        NaN             NaN             NaN      2.0         no   semi-furnished
44    7560000   6000.0       4.0        NaN      4.0        yes         no         no              no             yes      1.0        NaN        furnished
45    7560000   6000.0       3.0        2.0      3.0        yes         no         no              no             yes      0.0         no              NaN
46    7525000   6000.0       3.0        2.0      4.0        NaN         no          N              no             NaN      1.0         no        furnished
47    7490000   6600.0       3.0        1.0      4.0        yes         no        NaN             NaN             yes      3.0        NaN        furnished
48    7455000   4300.0       3.0        2.0      NaN        yes        NaN          y             NaN             NaN      NaN         no              NaN
49    7420000      NaN       3.0        NaN      1.0        yes        NaN        NaN              no            TRUE      0.0        NaN   semi-furnished
50    7420000      NaN       3.0        NaN      4.0        yes        NaN         no              no              no      NaN        NaN      unfurnished
51    7420000      NaN       3.0        NaN      4.0        yes          N        NaN              no             NaN      NaN       ille              NaN
52    7350000   6000.0       4.0        2.0      NaN        yes         Yo          N             NaN             yes      1.0         no        furnished
53    7350000      NaN       NaN        2.0      4.0        yes        NaN      FALSE              no             yes      2.0        NaN              NaN
54    7350000   6000.0       NaN        2.0      2.0        NaN        yes         no              no             NaN      1.0        NaN   semi-furnished
55    7350000   6000.0       3.0        1.0      2.0        yes      Nakko        NaN              no             NaN      1.0          N              NaN
56    7343000      NaN       NaN        1.0      2.0        yep          N        yes              no              no      NaN        yes   semi-furnished
57    7245000   9000.0       4.0        2.0      4.0        NaN        yes        NaN              no             yes      NaN        yes        furnished
58    7210000   7680.0       4.0        2.0      NaN        yes        NaN        NaN           Nakko             NaN      NaN         no              NaN
59    7210000   6000.0       3.0        2.0      4.0        yes        yes         no              no             NaN      1.0         no              NaN
60    7140000   6000.0       3.0        2.0      2.0        NaN          Y         no              no              no      NaN        NaN   semi-furnished
61    7070000      NaN       2.0        1.0      NaN        yes         no        NaN              no               y      NaN         no              NaN
62    7070000      NaN       4.0        2.0      NaN        yes          N        NaN              no             NaN      1.0        NaN        furnished
63    7035000      NaN       4.0        2.0      3.0        NaN       ille         no              no             NaN      2.0        yes        furnished
64    7000000  11175.0       NaN        1.0      NaN       TRUE         no       Haan              no             yes      NaN        NaN        furnished
65    6930000      NaN       3.0        2.0      2.0        yes        NaN        yes             NaN           ['y']      1.0         no        furnished
66    6930000      NaN       2.0        1.0      1.0        NaN         no        NaN             yes              no      1.0        NaN              NaN
67    6895000      NaN       NaN        2.0      1.0        NaN         no         no              no           Naaji      NaN         no      unfurnished
68    6860000   6000.0       NaN        1.0      1.0        yes         no         no             NaN             yes      NaN         no        furnished
69    6790000      NaN       NaN        2.0      2.0        yes         no        NaN              no              no      2.0        NaN        furnished
70    6790000      NaN       NaN        2.0      NaN        NaN        NaN        NaN              no             yes      0.0        NaN              NaN
71    6755000   6000.0       4.0        2.0      4.0        yes         no      FALSE              no             NaN      0.0         no      unfurnished
72    6720000   5020.0       NaN        NaN      4.0        yes         no      Nakko             NaN             yes      0.0        yes              NaN
73    6685000   6600.0       2.0        2.0      4.0        yes         no        NaN              no              no      NaN  Of course        furnished
74    6650000   4040.0       3.0        1.0      2.0        NaN         no        yes             NaN              no      NaN         no        furnished
75    6650000   4260.0       NaN        NaN      2.0        yes      Naaji         no             NaN             NaN      NaN        NaN   semi-furnished
76    6650000   6420.0       3.0        NaN      NaN        NaN        NaN        NaN              no             yes      NaN        yes        furnished
77    6650000   6500.0       3.0        NaN      NaN        yes         no        NaN              no               Y      0.0        yes        furnished
78    6650000   5700.0       3.0        NaN      1.0        yes        NaN        yes              no             NaN      NaN        yes              NaN
79    6650000      NaN       3.0        NaN      NaN        NaN        yes        NaN             NaN             yes      NaN         no        furnished
80    6629000   6000.0       NaN        NaN      2.0        yes          n         no             yes              no      NaN        NaN              NaN
81    6615000   4000.0       NaN        2.0      2.0        NaN         no        NaN             NaN             yes      1.0         no   semi-furnished
82    6615000      NaN       3.0        NaN      1.0        NaN         no        yes             NaN             yes      1.0        NaN        furnished
83    6580000   6000.0       NaN        2.0      NaN        yep         no       ille              no             NaN      NaN         no              NaN
84    6510000      NaN       3.0        NaN      NaN          y      FALSE         no             yes           ['n']      NaN        NaN              NaN
85    6510000   8250.0       3.0        2.0      3.0        yes         no        NaN             NaN             NaN      NaN        NaN        furnished
86    6510000      NaN       NaN        1.0      3.0        NaN        NaN        NaN               n               n      NaN        yes              NaN
87    6475000      NaN       3.0        1.0      1.0        NaN         no        yes              no             NaN      2.0         no              NaN
88    6475000   7410.0       3.0        NaN      1.0        yes        yes        yes              no             NaN      NaN        yes      unfurnished
89    6440000   8580.0       5.0        3.0      2.0          Y        NaN        Nah             NaN               N      NaN        NaN              NaN
90    6440000   5000.0       3.0        1.0      NaN        yes         no         no              no               y      0.0         no              NaN
91    6419000   6750.0       2.0        NaN      1.0        NaN        yes       TRUE           Naaji             NaN      2.0        NaN              NaN
92    6405000      NaN       3.0        2.0      4.0        NaN        yes         no             NaN             NaN      NaN         no        furnished
93    6300000   7200.0       3.0        2.0      1.0        yes         no        NaN             NaN             yes      NaN        NaN              NaN
94    6300000   6000.0       NaN        2.0      4.0        NaN      FALSE         no              no              no      NaN        NaN              NaN
95    6300000   4100.0       3.0        NaN      3.0        yes         no         no           FALSE             NaN      NaN        NaN              NaN
96    6300000   9000.0       3.0        1.0      1.0        yes      ['n']        yes              no              no      1.0        yes        furnished
97    6300000   6400.0       3.0        NaN      NaN        yes        NaN        yes             NaN             yes      1.0        NaN              NaN
98    6293000   6600.0       NaN        2.0      3.0        yes        NaN       ille              no             NaN      0.0        NaN      unfurnished
99    6265000      NaN       4.0        1.0      3.0        NaN        yes        NaN               n             NaN      NaN        NaN      unfurnished
100   6230000   6600.0       3.0        2.0      NaN      ['y']        NaN        NaN              no             yes      0.0        yes              NaN
101   6230000   5500.0       3.0        1.0      NaN        NaN         no         no            ille           Nakko      NaN        yes      unfurnished
102   6195000      NaN       3.0        NaN      4.0        yes       Haan         no              no             yes      NaN        NaN              NaN
103   6195000   6350.0       NaN        NaN      3.0        yes        yes        NaN              no             yep      0.0         no        furnished
104   6195000   5500.0       NaN        NaN      1.0        NaN        NaN        NaN             NaN             NaN      2.0        yes              NaN
105   6160000      NaN       3.0        1.0      4.0        yes        NaN         no              no             NaN      0.0         no      unfurnished
106   6160000   5450.0       4.0        2.0      1.0        NaN        NaN        yep              no             yes      0.0        yes   semi-furnished
107   6125000   6420.0       3.0        NaN      NaN        yes        NaN        yes              no              no      0.0        yes      unfurnished
108   6107500   3240.0       NaN        1.0      3.0          y        NaN        NaN             NaN             NaN      1.0        NaN   semi-furnished
109   6090000      NaN       4.0        2.0      NaN        yes        NaN        NaN             yes              no      1.0         no   semi-furnished
110   6090000      NaN       NaN        NaN      NaN        yes        yes        yes             NaN              no      2.0        NaN   semi-furnished
111   6090000      NaN       NaN        1.0      3.0          Y         no         no              no             yes      2.0         no      unfurnished
112   6083000   4300.0       6.0        2.0      2.0        yes         no        NaN             NaN              no      0.0         no        furnished
113   6083000   9620.0       3.0        1.0      1.0        NaN         no        yes             NaN             Nah      2.0        yes        furnished
114   6020000   6800.0       NaN        1.0      NaN        yes        NaN        yes           Naaji           Naaji      2.0         no              NaN
115   6020000   8000.0       3.0        NaN      NaN        NaN        NaN        yes            Nope             yes      2.0        yes   semi-furnished
116   6020000   6900.0       NaN        2.0      1.0        NaN        yes        NaN              no             NaN      0.0        NaN      unfurnished
117   5950000      NaN       NaN        1.0      2.0        yes        NaN         no              no             NaN      0.0         no        furnished
118   5950000   6420.0       3.0        NaN      1.0        yes        NaN        NaN              no             yep      NaN        NaN        furnished
119   5950000      NaN       NaN        1.0      NaN        yes         no        NaN              no             NaN      NaN        yes              NaN
120   5950000   6540.0       3.0        NaN      1.0        yes        NaN        NaN              no              no      2.0        yes        furnished
121   5950000   7231.0       3.0        1.0      2.0        yes        NaN        NaN              no             yes      NaN        yes              NaN
122   5950000   6254.0       NaN        2.0      1.0        NaN        NaN        yes             NaN              no      NaN        yep   semi-furnished
123   5950000      NaN       NaN        NaN      2.0        NaN        NaN         no              no             NaN      NaN      Nakko              NaN
124   5950000   6525.0       NaN        2.0      NaN        yes         no        NaN              no             NaN      1.0        NaN        furnished
125   5943000  15600.0       3.0        NaN      1.0        yes        Nah        NaN             NaN             yes      NaN         no              NaN
126   5880000   7160.0       3.0        1.0      1.0       TRUE          n        NaN             NaN              no      NaN          y      unfurnished
127   5880000   6500.0       NaN        NaN      3.0        NaN         no         no             Nah             yes      NaN         no              NaN

tells the sum of null values in specific column to confirm their presence accordingly

In [22]:
df.isnull().sum()

price                 0
area                206
bedrooms            187
bathrooms           183
stories             185
mainroad            194
guestroom           210
basement            204
hotwaterheating     204
airconditioning     188
parking             208
prefarea            188
furnishingstatus    187
dtype: int64

telling data types of each column to understand its nature

In [23]:
df.dtypes

price                 int64
area                float64
bedrooms            float64
bathrooms           float64
stories             float64
mainroad             object
guestroom            object
basement             object
hotwaterheating      object
airconditioning      object
parking             float64
prefarea             object
furnishingstatus     object
dtype: object

removing duplicate rows if any for smooth functioning

In [24]:
df=df.drop_duplicates()
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420.0,4.0,NaN,3.0,NaN,NaN,NaN,NaN,yes,2.0,Haanji,furnished
1,12250000,8960.0,NaN,4.0,4.0,yes,no,no,Nakko,yes,NaN,no,furnished
2,12250000,9960.0,3.0,2.0,2.0,yes,NaN,yes,no,Naaji,2.0,yes,semi-furnished
3,12215000,7500.0,NaN,NaN,NaN,NaN,no,yes,no,yes,3.0,yes,furnished
4,11410000,7420.0,NaN,1.0,2.0,NaN,Of course,yes,NaN,yes,2.0,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,NaN,2.0,NaN,1.0,NaN,no,NaN,no,no,NaN,no,unfurnished
541,1767150,NaN,3.0,1.0,1.0,no,ille,no,no,Nah,NaN,NaN,NaN
542,1750000,3620.0,NaN,NaN,NaN,yes,no,no,NaN,NaN,NaN,n,unfurnished
543,1750000,NaN,NaN,1.0,1.0,no,no,no,no,no,0.0,NaN,furnished
544,1750000,3850.0,3.0,1.0,2.0,NaN,NaN,NaN,NaN,no,0.0,Naaji,NaN

removing rows if any that contain entire null values as such rows only reduce efficiency of the model

In [25]:
df.dropna(how='all')

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420.0,4.0,NaN,3.0,NaN,NaN,NaN,NaN,yes,2.0,Haanji,furnished
1,12250000,8960.0,NaN,4.0,4.0,yes,no,no,Nakko,yes,NaN,no,furnished
2,12250000,9960.0,3.0,2.0,2.0,yes,NaN,yes,no,Naaji,2.0,yes,semi-furnished
3,12215000,7500.0,NaN,NaN,NaN,NaN,no,yes,no,yes,3.0,yes,furnished
4,11410000,7420.0,NaN,1.0,2.0,NaN,Of course,yes,NaN,yes,2.0,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,NaN,2.0,NaN,1.0,NaN,no,NaN,no,no,NaN,no,unfurnished
541,1767150,NaN,3.0,1.0,1.0,no,ille,no,no,Nah,NaN,NaN,NaN
542,1750000,3620.0,NaN,NaN,NaN,yes,no,no,NaN,NaN,NaN,n,unfurnished
543,1750000,NaN,NaN,1.0,1.0,no,no,no,no,no,0.0,NaN,furnished
544,1750000,3850.0,3.0,1.0,2.0,NaN,NaN,NaN,NaN,no,0.0,Naaji,NaN

extracting unique values of each column

In [26]:
print(df['stories'].unique())
print(df['bedrooms'].unique())
print(df['bathrooms'].unique())
print(df['mainroad'].unique())
print(df['guestroom'].unique())
print(df['basement'].unique())
print(df['hotwaterheating'].unique())
print(df['airconditioning'].unique())
print(df['parking'].unique())
print(df['prefarea'].unique())
print(df['furnishingstatus'].unique())

[ 3.  4.  2. nan  1.]
[ 4. nan  3.  5.  2.  6.  1.]
[nan  4.  2.  1.  3.]
[nan 'yes' 'Of course' 'Indeed' 'yep' 'Haan' 'TRUE' 'y' 'Y' "['y']" 'Nope'
 'Yo' 'no' 'Haanji' 'Nakko' 'FALSE' 'Naaji' 'N' 'n']
[nan 'no' 'Of course' 'yes' 'ille' 'y' 'N' 'Yo' 'Nakko' 'Y' 'Naaji' 'n'
 'FALSE' "['n']" 'Haan' 'Nah' 'yep' 'Haanji' 'TRUE' 'Nope' 'Indeed']
[nan 'no' 'yes' 'Haanji' 'N' 'Naaji' 'n' 'y' 'FALSE' 'Haan' 'Nakko' 'ille'
 'Nah' 'TRUE' 'yep' 'Nope' 'Indeed' "['n']" 'Of course' 'Y' 'Yo']
[nan 'Nakko' 'no' 'Nope' 'yes' 'Nah' 'Y' 'n' 'FALSE' 'Naaji' 'ille' 'N'
 "['n']" 'Haan' 'y']
['yes' 'Naaji' 'no' nan 'yep' 'y' 'TRUE' "['y']" 'Y' "['n']" 'n' 'N'
 'Nakko' 'Nah' 'ille' 'FALSE' 'Nope' 'Of course' 'Haanji']
[ 2. nan  3.  0.  1.]
['Haanji' 'no' 'yes' 'Haan' nan 'Of course' 'Nakko' 'Nope' 'ille' 'N'
 'yep' 'y' 'Naaji' 'TRUE' 'Y' 'n' "['n']" 'FALSE' 'Yo' 'Nah']
['furnished' 'semi-furnished' nan 'unfurnished']

columns such as mainroom,guestroom,basement,hotwaterheating,airconditioning,parking contains some data in wrong format that was accordingly replaced with the correct format data as needed by the model

In [27]:
wtrue=["Of course" ,"Indeed", "yep" ,"Haan" ,"True" ,"y", "Y", "['y']","Yo","Haanji"]
rtrue='yes'
wfalse=["Nope","Nakko","False" ,"Naaji", "N" ,"n","ille","N","['n']","Nah"]
rfalse='no'
df['mainroad']=df['mainroad'].replace(wtrue,rtrue)
df['mainroad']=df['mainroad'].replace(wfalse,rfalse)
df['guestroom']=df['guestroom'].replace(wtrue,rtrue)
df['guestroom']=df['guestroom'].replace(wfalse,rfalse)
df['basement']=df['basement'].replace(wtrue,rtrue)
df['basement']=df['basement'].replace(wfalse,rfalse)
df['hotwaterheating']=df['hotwaterheating'].replace(wtrue,rtrue)
df['hotwaterheating']=df['hotwaterheating'].replace(wfalse,rfalse)
df['airconditioning']=df['airconditioning'].replace(wtrue,rtrue)
df['airconditioning']=df['airconditioning'].replace(wfalse,rfalse)
df['parking']=df['parking'].replace(wtrue,rtrue)
df['parking']=df['parking'].replace(wfalse,rfalse)
df['prefarea']=df['prefarea'].replace(wtrue,rtrue)
df['prefarea']=df['prefarea'].replace(wfalse,rfalse)
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420.0,4.0,NaN,3.0,NaN,NaN,NaN,NaN,yes,2.0,yes,furnished
1,12250000,8960.0,NaN,4.0,4.0,yes,no,no,no,yes,NaN,no,furnished
2,12250000,9960.0,3.0,2.0,2.0,yes,NaN,yes,no,no,2.0,yes,semi-furnished
3,12215000,7500.0,NaN,NaN,NaN,NaN,no,yes,no,yes,3.0,yes,furnished
4,11410000,7420.0,NaN,1.0,2.0,NaN,yes,yes,NaN,yes,2.0,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,NaN,2.0,NaN,1.0,NaN,no,NaN,no,no,NaN,no,unfurnished
541,1767150,NaN,3.0,1.0,1.0,no,no,no,no,no,NaN,NaN,NaN
542,1750000,3620.0,NaN,NaN,NaN,yes,no,no,NaN,NaN,NaN,no,unfurnished
543,1750000,NaN,NaN,1.0,1.0,no,no,no,no,no,0.0,NaN,furnished
544,1750000,3850.0,3.0,1.0,2.0,NaN,NaN,NaN,NaN,no,0.0,no,NaN

for numeric column best approach is to extract the most common value along with its frequency to understand the variation.for this below function is made

In [28]:
for col in ["area","bedrooms","bathrooms","stories","parking"]:
    print(col)
    print(df[col].value_counts(normalize=True).sort_values(ascending=False).head())
    print("---------")

area
area
6000.0    0.047198
4500.0    0.020649
4000.0    0.020649
6600.0    0.017699
3000.0    0.017699
Name: proportion, dtype: float64
---------
bedrooms
bedrooms
3.0    0.544693
2.0    0.268156
4.0    0.170391
5.0    0.011173
6.0    0.002793
Name: proportion, dtype: float64
---------
bathrooms
bathrooms
1.0    0.756906
2.0    0.223757
3.0    0.016575
4.0    0.002762
Name: proportion, dtype: float64
---------
stories
stories
2.0    0.450000
1.0    0.386111
4.0    0.083333
3.0    0.080556
Name: proportion, dtype: float64
---------
parking
parking
0.0    0.560831
1.0    0.216617
2.0    0.201780
3.0    0.020772
Name: proportion, dtype: float64
---------

interpolate method is used for the numeric columns to fill null values with an estimated value based on the immediate value.along with this i used fillna method to replace the missing blocks left after interpolation with the most ocurred value

In [29]:
df['area']=df['area'].interpolate(method='linear').fillna(1).astype(int)
df['bedrooms']=df['bedrooms'].interpolate(method='linear').fillna(3).astype(int)
df['bathrooms']=df['bathrooms'].interpolate(method='linear').fillna(1).astype(int)
df['stories']=df['stories'].interpolate(method='linear').fillna(2).astype(int)
df['parking']=df['parking'].interpolate(method='linear').fillna(0).astype(int)
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,1,3,NaN,NaN,NaN,NaN,yes,2,yes,furnished
1,12250000,8960,3,4,4,yes,no,no,no,yes,2,no,furnished
2,12250000,9960,3,2,2,yes,NaN,yes,no,no,2,yes,semi-furnished
3,12215000,7500,3,1,2,NaN,no,yes,no,yes,3,yes,furnished
4,11410000,7420,3,1,2,NaN,yes,yes,NaN,yes,2,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3634,2,1,1,NaN,no,NaN,no,no,0,no,unfurnished
541,1767150,3627,3,1,1,no,no,no,no,no,0,NaN,NaN
542,1750000,3620,3,1,1,yes,no,no,NaN,NaN,0,no,unfurnished
543,1750000,3735,3,1,1,no,no,no,no,no,0,NaN,furnished
544,1750000,3850,3,1,2,NaN,NaN,NaN,NaN,no,0,no,NaN

among the rest column mainroad and hotwaterheating have pattern that was most repeated with yes or no.so accordingly the null values have been placed.

In [30]:
df['mainroad'].fillna('yes',inplace=True)
df['hotwaterheating'].fillna('no',inplace=True)
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,1,3,yes,NaN,NaN,no,yes,2,yes,furnished
1,12250000,8960,3,4,4,yes,no,no,no,yes,2,no,furnished
2,12250000,9960,3,2,2,yes,NaN,yes,no,no,2,yes,semi-furnished
3,12215000,7500,3,1,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,3,1,2,yes,yes,yes,no,yes,2,no,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3634,2,1,1,yes,no,NaN,no,no,0,no,unfurnished
541,1767150,3627,3,1,1,no,no,no,no,no,0,NaN,NaN
542,1750000,3620,3,1,1,yes,no,no,no,NaN,0,no,unfurnished
543,1750000,3735,3,1,1,no,no,no,no,no,0,NaN,furnished
544,1750000,3850,3,1,2,yes,NaN,NaN,no,no,0,no,NaN

for the rest columns no such above pattern was observed so i changed them to numeric value using replace method and then observed the frequency of the most occured

In [31]:
df['guestroom'].replace(['yes','YES','no','NO'],[1,1,0,0],inplace=True)
df['basement'].replace(['yes','YES','no','NO'],[1,1,0,0],inplace=True)
df['airconditioning'].replace(['yes','YES','no','NO'],[1,1,0,0],inplace=True)
df['prefarea'].replace(['yes','YES','no','NO'],[1,1,0,0],inplace=True)
df['furnishingstatus'].replace(['furnished','semi-furnished','unfurnished'],[1,0.5,0],inplace=True)
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,1,3,yes,NaN,NaN,no,1,2,1,1.0
1,12250000,8960,3,4,4,yes,0,0,no,1,2,0,1.0
2,12250000,9960,3,2,2,yes,NaN,1,no,0,2,1,0.5
3,12215000,7500,3,1,2,yes,0,1,no,1,3,1,1.0
4,11410000,7420,3,1,2,yes,1,1,no,1,2,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3634,2,1,1,yes,0,NaN,no,0,0,0,0.0
541,1767150,3627,3,1,1,no,0,0,no,0,0,NaN,NaN
542,1750000,3620,3,1,1,yes,0,0,no,NaN,0,0,0.0
543,1750000,3735,3,1,1,no,0,0,no,0,0,NaN,1.0
544,1750000,3850,3,1,2,yes,NaN,NaN,no,0,0,0,NaN

In [32]:
for col in ["guestroom","airconditioning","basement","prefarea","furnishingstatus"]:
    print(col)
    print(df[col].value_counts(normalize=True).sort_values(ascending=False).head())
    print("---------")

guestroom
guestroom
0        0.782090
1        0.188060
FALSE    0.026866
TRUE     0.002985
Name: proportion, dtype: float64
---------
airconditioning
airconditioning
0        0.630252
1        0.344538
FALSE    0.016807
TRUE     0.008403
Name: proportion, dtype: float64
---------
basement
basement
0        0.648094
1        0.328446
FALSE    0.011730
TRUE     0.011730
Name: proportion, dtype: float64
---------
prefarea
prefarea
0        0.764706
1        0.218487
FALSE    0.014006
TRUE     0.002801
Name: proportion, dtype: float64
---------
furnishingstatus
furnishingstatus
0.5    0.388268
0.0    0.326816
1.0    0.284916
Name: proportion, dtype: float64
---------

replacing null with most occured gives a chance of 99% correctness and with any number gives a chance of 0% correctness

In [33]:
df["guestroom"].fillna(0, inplace = True)
df["airconditioning"].fillna(0, inplace = True)
df["basement"].fillna(0, inplace = True)
df["prefarea"].fillna(0, inplace = True)
df["furnishingstatus"].fillna(0.5, inplace = True)
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,1,3,yes,0,0,no,1,2,1,1.0
1,12250000,8960,3,4,4,yes,0,0,no,1,2,0,1.0
2,12250000,9960,3,2,2,yes,0,1,no,0,2,1,0.5
3,12215000,7500,3,1,2,yes,0,1,no,1,3,1,1.0
4,11410000,7420,3,1,2,yes,1,1,no,1,2,0,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3634,2,1,1,yes,0,0,no,0,0,0,0.0
541,1767150,3627,3,1,1,no,0,0,no,0,0,0,0.5
542,1750000,3620,3,1,1,yes,0,0,no,0,0,0,0.0
543,1750000,3735,3,1,1,no,0,0,no,0,0,0,1.0
544,1750000,3850,3,1,2,yes,0,0,no,0,0,0,0.5